//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public int MetaData_ID { get; set; }
        public string Post_ID { get; set; }
        public Nullable<double> Face_Age { get; set; }
        public string Face_Gender { get; set; }
        public Nullable<bool> Face_IsGlasses { get; set; }
        public string Face_ID { get; set; }
        public string Face_Rectangle { get; set; }
    }
}
