//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFDSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Post_Serial { get; set; }
        public string Post_ID { get; set; }
        public Nullable<System.DateTime> Post_Date { get; set; }
        public string Post_Caption { get; set; }
        public Nullable<decimal> Location_Longitude { get; set; }
        public Nullable<decimal> Location_Latitude { get; set; }
        public string Location_Name { get; set; }
        public string Image_Thumbnail_Url { get; set; }
        public string Image_Standard_Url { get; set; }
        public string Image_LowResolution_Url { get; set; }
    }
}
